DB2_blog_post/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('posts.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from .views import (Signup, SignIn, SignOut,
                    Activate, UserDetail, EmailVerificationNotice)
from django.urls import path

app_name = 'accounts'

urlpatterns = [
    path('sign-up/', Signup.as_view(), name='sign-up'),
    path('sign-in/', SignIn.as_view(), name='sign-in'),
    path('sign-out/', SignOut.as_view(), name='sign-out'),
    path('activate/<str:uid>/<str:token>', Activate.as_view(), name='activate'),
    path('verification-notice/',
         EmailVerificationNotice.as_view(), name='notice'),
    path('my-account/', UserDetail.as_view(), name='detail'),
]

posts/urls.py
from .views import PostCreateView, PostDetailView, PostListView, PostLikeView
from django.urls import path

app_name = 'posts'

urlpatterns = [
    path('create/', PostCreateView.as_view(), name='new-post'),
    path('', PostListView.as_view(), name='list'),
    path('<int:pk>/', PostDetailView.as_view(), name='detail'),
    path('like/<int:post_id>/', PostLikeView.as_view(), name='like'),
]

accounts/models.py
from django.contrib.auth.models import BaseUserManager
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.core.mail import send_mail
from django.db import models
from django.utils.translation import ugettext_lazy as _


class MyUserManager(BaseUserManager):
    """
    A custom user manager to deal with emails as unique identifiers for auth
    instead of usernames. The default that's used is "UserManager"
    """
    def _create_user(self, email, password, **extra_fields):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError('The Email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True, null=True)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    birthday = models.DateField(null=True, blank=True)
    country = models.CharField(max_length=30, blank=True)
    city = models.CharField(max_length=30, blank=True)

    USERNAME_FIELD = 'email'
    objects = MyUserManager()

    def __str__(self):
        return self.email

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.email

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this User."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

accounts/forms.py
from django import forms
from django.forms import widgets

from .models import User


class LoginForm(forms.Form):
    """The simple form for log in into website and get all main features
    """
    email = forms.EmailField()
    password = forms.CharField(min_length=6, widget=forms.PasswordInput,
                               required=True)


class UserSignupForm(forms.ModelForm):
    """The form for creating new users for sign up on template.
    Includes all the required fields, plus a repeated password
    and send email verification for account activation.
    """
    birthday = forms.DateField(label='Birthday', widget=widgets.DateInput)
    password1 = forms.CharField(label='Password', max_length=60,
                                widget=widgets.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', max_length=60,
                                widget=widgets.PasswordInput)

    class Meta:
        model = User
        fields = ('email', 'country', 'city')

    def clean_password2(self):
        # Confirm if given password matched.
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('Passwords don\'t match')
        return password2

accounts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth import (get_user_model, login, logout,
                                 authenticate, update_session_auth_hash)
from django.contrib.auth.forms import PasswordChangeForm
from django.http import HttpResponse
from django.shortcuts import render, redirect, reverse, HttpResponseRedirect
from django.views import View
from django.views.generic import CreateView, TemplateView
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode

from .forms import UserSignupForm, LoginForm
from .tokens import account_activation_token

User = get_user_model()


class Signup(CreateView):
    form_class = UserSignupForm
    success_url = reverse_lazy('accounts:notice')
    template_name = 'accounts/sign-up.html'

    def form_valid(self, form, commit=True):
        # Save the provided password in hashed format
        user = form.save(commit=False)
        user.set_password(form.cleaned_data['password1'])
        if commit:
            user.save()
            # Prepare email activation content
            current_site = get_current_site(self.request)
            subject = 'Activate your account'
            message = render_to_string('accounts/activation-email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': force_text(urlsafe_base64_encode(force_bytes(user.pk))),
                'token': account_activation_token.make_token(user),
            })
            user.email_user(subject, message)
        return super().form_valid(form)

    def dispatch(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            # Redirect to home page since this user is already authenticated
            return redirect('accounts:detail')
        return super().dispatch(*args, **kwargs)


class SignIn(View):

    def get(self, request):
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse('accounts:detail'))
        else:
            form = LoginForm()
            return render(request, 'accounts/sign-in.html', {'form': form})

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = authenticate(
                email=data.get('email'),
                password=data.get('password'))
            if user:
                login(request, user)
                return HttpResponseRedirect(reverse('accounts:detail'))
        return render(request, 'accounts/sign-in.html', {'form': form})


class SignOut(View):

    def get(self, request):
        logout(request)
        return HttpResponseRedirect(reverse('accounts:sign-in'))


class UserDetail(LoginRequiredMixin, TemplateView):
    login_url = reverse_lazy('accounts:sign-in')
    template_name = 'accounts/my-account.html'


class EmailVerificationNotice(TemplateView):
    template_name = 'accounts/email-verification-notice.html'

    def dispatch(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            # Redirect to home page since this user is already authenticated
            return redirect('accounts:detail')
        return super().dispatch(*args, **kwargs)


class Activate(View):
    def get(self, request, uid, token):
        try:
            _uid = force_text(urlsafe_base64_decode(uid))
            user = User.objects.get(pk=_uid)
        except(TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None
        if user is not None \
                and account_activation_token.check_token(user, token):
            # Activate user and login:
            user.is_active = True
            user.save()
            login(request, user)
            PasswordChangeForm(request.user)
            return HttpResponseRedirect(reverse('accounts:detail'))
        else:
            return HttpResponse('Activation link is invalid!')

    def post(self, request):
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return HttpResponse('Password changed successfully')

accounts/templates/accounts/activation-email.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

http://{{ domain }}{% url 'accounts:activate' uid=uid token=token %}
{% endautoescape %}

accounts/templates/accounts/email-verification-notice.html
{% extends 'base.html' %}

{% block title %} - Verify your email {% endblock %}

{% block content %}
     <div class="mdl-grid mdl-layout-center mdl-padding-large">
	     <div class="mdl-cell mdl-cell--5-col">
		     <h1>Verify your email</h1>
		     <p>
			     We have sent an e-mail to you for verification. Follow the link provided to finalize the signup
			     process.
		     </p>
	     </div>
     </div>
{% endblock %}

accounts/templates/accounts/my-account.html
{% extends 'base.html' %}

{% block title %} - My Account{% endblock %}

{% block content %}
	<div class="mdl-grid mdl-layout-center mdl-padding-large">
		<div class="mdl-cell mdl-cell--4-col">
			<h1 class="mdl-typography--subhead">My Account</h1>
			<div class="mdl-grid">
				<span class="mdl-cell mdl-cell--8-col mdl-typography--body-2">Email</span>
				<span class="mdl-cell mdl-cell--4-col mdl-typography--body-1">{{ user.email }}</span>
			</div>
			<div class="mdl-grid">
				<span class="mdl-cell mdl-cell--8-col mdl-typography--body-2">Birthday</span>
				<span class="mdl-cell mdl-cell--4-col mdl-typography--body-1">{{ user.birthday }}</span>
			</div>
			<div class="mdl-grid">
				<span class="mdl-cell mdl-cell--8-col mdl-typography--body-2">Country</span>
				<span class="mdl-cell mdl-cell--4-col mdl-typography--body-1">{{ user.country }}</span>
			</div>
            <div class="mdl-grid">
				<span class="mdl-cell mdl-cell--8-col mdl-typography--body-2">City</span>
				<span class="mdl-cell mdl-cell--4-col mdl-typography--body-1">{{ user.city }}</span>
			</div>
		</div>
	</div>
{% endblock %}

accounts/templates/accounts/sign-in.html
{% extends 'base.html' %}

{% block title %} - Sign-in {% endblock %}

{% block login %}
	    <div class="container">
        <h1>Sign in please</h1>
        <form action="{% url 'accounts:sign-in' %}" method="POST">
            {% csrf_token %}

            {% for error in form.non_field_errors %}
                {{ error|escape }}
            {% endfor %}

            {% if form.email.errors %}
                {{ form.email.errors }}
            {% endif %}
            <p>Email</p>
            {{ form.email }}

            {% if form.password.errors %}
                {{ form.password.errors }}
            {% endif %}
            <p>Password</p>
            {{ form.password }}
            <input type="submit">
        </form>
    </div>
{% endblock %}

accounts/templates/accounts/sign-up.html
{% extends 'base.html' %}

{% block title %} - Sign up{% endblock %}

{% block content %}
<div class="mdl-grid mdl-layout-center mdl-padding-large">
	<div class="mdl-cell mdl-card mdl-cell--4-col mdl-card mdl-shadow--2dp">
		<div class="mdl-card__title">
			<h2 class="mdl-card__title-text">Sign up</h2>
		</div>
		<div class="mdl-card__supporting-text">
			<form method="post">
				{% csrf_token %}
				{% for field in form %}

				<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-width-100">
					<input class="mdl-textfield__input"
					       type="{% if field.id_for_label == 'id_password2' or field.id_for_label == 'id_password1' %}password{% else %}text{% endif %}"
					       name="{{ field.html_name }}"
					       id="{{ field.id_for_label }}">
					<label class="mdl-textfield__label" for="{{ field.id_for_label }}">{{ field.label }}</label>
				</div>
				{% for error in field.errors %}
				<span class="mdl-typography--caption mdl-color-text--red-500">{{ error }}</span>
				{% endfor %}

				{% if field.help_text %}
				<p class="mdl-typography--body-1">{{ field.help_text|safe }}</p>
				{% endif %}
				{% endfor %}
				<div class="mdl-padding-top-medium">
					<button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent"
					        type="submit">Sign up
					</button>
				</div>
			</form>
		</div>
	</div>
</div>
{% endblock %}