DB2_blog_post/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('posts.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from .views import PostCreateView, PostDetailView, PostListView, PostLikeView
from django.urls import path

app_name = 'posts'

urlpatterns = [
    path('create/', PostCreateView.as_view(), name='new-post'),
    path('', PostListView.as_view(), name='list'),
    path('<int:pk>/', PostDetailView.as_view(), name='detail'),
    path('like/<int:post_id>/', PostLikeView.as_view(), name='like'),
]

DB2_blog_post/posts/models.py
from django.db import models
from django.conf import settings


class Post(models.Model):
    title = models.CharField(max_length=60, null=False, blank=False)
    body = models.TextField()
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='author',
        on_delete=models.CASCADE
    )
    post_image = models.FileField(upload_to='post_images/',
                              blank=True, null=True)
    document = models.FileField(upload_to='documents/', blank=True, null=True)
    liked_by = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                      related_name='liked')
    added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.title} | {self.body} | {self.author} | {self.liked_by}'


class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               related_name="comment_author",
                               on_delete=models.CASCADE)
    post = models.ForeignKey(Post, related_name="comments",
                             null=True, on_delete=models.CASCADE)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True, null=True)

    class Meta:
        unique_together = ("author", "post")

    def __str__(self):
        return f"{self.author} | {self.post}"

posts/models.py
from django.db import models
from django.conf import settings


class Post(models.Model):
    title = models.CharField(max_length=60, null=False, blank=False)
    body = models.TextField()
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='author',
        on_delete=models.CASCADE
    )
    post_image = models.FileField(upload_to='post_images/',
                              blank=True, null=True)
    liked_by = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                      related_name='liked')
    added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.title} | {self.body} | {self.author} | {self.liked_by}'


class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               related_name="comment_author",
                               on_delete=models.CASCADE)
    post = models.ForeignKey(Post, related_name="comments",
                             null=True, on_delete=models.CASCADE)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True, null=True)

    class Meta:
        unique_together = ("author", "post")

    def __str__(self):
        return f"{self.author} | {self.post}"

DB2_blog_post/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'body', 'post_image', 'document',)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'body', 'post_image',)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

DB2_blog_post/posts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Count
from django.shortcuts import get_object_or_404, reverse, HttpResponseRedirect
from django.views.generic import ListView, DetailView, CreateView, View
from django.views.generic.edit import FormMixin
from django.urls import reverse_lazy


from .forms import PostForm, CommentForm
from .models import Post


class PostCreateView(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('accounts:sign-in')
    template_name = 'posts/new_post.html'
    form_class = PostForm
    queryset = Post.objects.all()
    success_url = '/'

    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        return super(PostCreateView, self).form_valid(form)


class PostDetailView(LoginRequiredMixin, FormMixin, DetailView):
    login_url = reverse_lazy('accounts:sign-in')
    template_name = 'posts/post_detail.html'
    model = Post
    form_class = CommentForm

    def get_queryset(self):
        return Post.objects.all()

    def get_success_url(self):
        return reverse('posts:detail', kwargs={'pk': self.object.id})

    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        context['form'] = CommentForm(initial={'post': self.object})
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        form.instance.post_id = self.object.id
        form.save()
        return super(PostDetailView, self).form_valid(form)


class PostListView(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('accounts:sign-in')
    template_name = 'posts/posts_list.html'
    context_object_name = "posts_list"
    paginate_by = 2

    def get_queryset(self):
        filter_value = self.request.GET.get('filter', '')
        order = self.request.GET.get('order_by', 'added')
        if filter_value:
            new_context = Post.objects.filter(title__contains=filter_value)
        elif order == 'liked_by' or order == '-liked_by':
            new_context = Post.objects.annotate(
                liked_by_count=Count('liked_by')).order_by(f'{order}_count')
        else:
            new_context = Post.objects.all().order_by(order)
        return new_context


class PostLikeView(LoginRequiredMixin, View):
    login_url = reverse_lazy('accounts:sign-in')

    def get(self, request, post_id):
        post = get_object_or_404(Post, id=post_id)
        if request.user in post.liked_by.all():
            post.liked_by.remove(request.user)
        else:
            post.liked_by.add(request.user)
        post.save()
        return HttpResponseRedirect(
            reverse('posts:detail', kwargs={'pk': post_id})
        )

posts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Count
from django.shortcuts import get_object_or_404, reverse, HttpResponseRedirect
from django.views.generic import ListView, DetailView, CreateView, View
from django.views.generic.edit import FormMixin
from django.urls import reverse_lazy


from .forms import PostForm, CommentForm
from .models import Post


class PostCreateView(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('accounts:sign-in')
    template_name = 'posts/new_post.html'
    form_class = PostForm
    queryset = Post.objects.all()
    success_url = '/'

    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        return super(PostCreateView, self).form_valid(form)


class PostDetailView(LoginRequiredMixin, FormMixin, DetailView):
    login_url = reverse_lazy('accounts:sign-in')
    template_name = 'posts/post_detail.html'
    model = Post
    form_class = CommentForm

    def get_queryset(self):
        return Post.objects.all()

    def get_success_url(self):
        return reverse('posts:detail', kwargs={'pk': self.object.id})

    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        context['form'] = CommentForm(initial={'post': self.object})
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        form.instance.post_id = self.object.id
        form.save()
        return super(PostDetailView, self).form_valid(form)


class PostListView(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('accounts:sign-in')
    template_name = 'posts/posts_list.html'
    context_object_name = "posts_list"
    paginate_by = 20

    def get_queryset(self):
        filter_value = self.request.GET.get('filter', '')
        order = self.request.GET.get('order_by', 'added')
        if filter_value:
            new_context = Post.objects.filter(title__contains=filter_value)
        elif order == 'liked_by' or order == '-liked_by':
            new_context = Post.objects.annotate(
                liked_by_count=Count('liked_by')).order_by(f'{order}_count')
        else:
            new_context = Post.objects.all().order_by(order)
        return new_context


class PostLikeView(LoginRequiredMixin, View):
    login_url = reverse_lazy('accounts:sign-in')

    def get(self, request, post_id):
        post = get_object_or_404(Post, id=post_id)
        if request.user in post.liked_by.all():
            post.liked_by.remove(request.user)
        else:
            post.liked_by.add(request.user)
        post.save()
        return HttpResponseRedirect(
            reverse('posts:detail', kwargs={'pk': post_id})
        )

DB2_blog_post/posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block content %}

    <div class="jumbotron">
        <div class="container">
            <h1>{{ post.title }}</h1>
            <p>{{ post.body }}</p>
            <p>{{ post.image }}</p>
            <p>{{ post.liked_by }}</p>
            <p>{{ post.added }}</p>
            <a class="waves-effect waves-light btn" href="{% url 'posts:like' post.id %}">
                {% if request.user in post.liked_by.all %}
                    Unlike {{ post.liked_by.all.count }}
                {% else %}
                    Like {{ post.liked_by.all.count }}
                {% endif %}
            </a>
        </div>
    </div>
    {% for comment in post.comments.all %}
        <div>{{ comment.date }} {{ comment.author }}</div>
        <div>{{ comment.body }}</div>
    {% empty %}
        <p>No comments here yet.</p>
    {% endfor %}
    <h1>New comment</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <hr>
        <button type="submit" class="btn btn-primary">Comment</button>
    </form>


    <div class="container">
        {#        <a href="{% url 'news:feeds-create' %}" class="btn btn-primary">New Feed</a>#}


    </div>

{% endblock %}

DB2_blog_post/posts/templates/posts/posts_list.html
{% extends 'base.html' %}

{% block content %}

    <div class="jumbotron">
        <div class="container">
            <h1>Posts</h1>
            <p>Have a look around to see some of the latest and greatest posts</p>
        </div>
    </div>
    <div>Order by</div>
    <div>
        <a class="waves-effect waves-light btn" href="{% url 'posts:list' %}?order_by=-added">recently added posts</a>
    </div>
    <div>
        <a class="waves-effect waves-light btn" href="{% url 'posts:list' %}?order_by=added">lately added posts</a>
    </div>
    <div>
        <a class="waves-effect waves-light btn" href="{% url 'posts:list' %}?order_by=title">posts title</a>
    </div>
    <div>
        <a class="waves-effect waves-light btn" href="{% url 'posts:list' %}?order_by=liked_by">most liked title</a>
    </div>
    <div>
        <a class="waves-effect waves-light btn" href="{% url 'posts:list' %}?order_by=-liked_by">least liked title</a>
    </div>
    <form action="{% url 'posts:list' %}" method="GET">
            <div class="row">
                <h5>Search post by title: </h5>
                <div class="input-field">
                    <input type="text" name="filter" />
                </div>
                <button type="submit" class="waves-effect waves-light btn">Search</button>
            </div>
        </form>
    {#    <form method="get" action="{% url 'posts:list' %}">#}
    {#        <p>order_by: <input type="text" value="-added" name="orderby" /></p>#}
    {#        <p><input type="submit" name="submit" value="submit"/></p>#}
    {#    </form>#}
    <div class="container">
        {% for post in object_list %}
            <p><b>Title:</b> {{ post.title }}</p>
            <p><b>Body:</b> {{ post.body }}</p>
            <p><b>Author:</b> {{ post.author }}</p>
            {{ post.document }}
            <p><b>Image:</b> <img src="{{ post.post_image }}" alt="image"></p>
            <p><b>Post added:</b>
                {% if post.added %}
                    {{ post.added }}
                {% else %}
                    Publication date not set on post
                {% endif %}
            </p>
            <div><a class="waves-effect waves-light btn" href="{% url 'posts:detail' post.id %}">More</a></div>
            <a class="waves-effect waves-light btn" href="{% url 'posts:like' post.id %}">
                {% if request.user in post.liked_by.all %}
                    Unlike {{ post.liked_by.all.count }}
                {% else %}
                    Like {{ post.liked_by.all.count }}
                {% endif %}
            </a>
            <hr>

            </div>
        {% endfor %}
    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{% url 'posts:list' %}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{% url 'posts:list' %}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
    {% if not object_list %}
        <p>There is not posts yet)</p>
    {% endif %}

{% endblock %}