DB2_blog_post/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('posts.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from .views import (Signup, SignIn, SignOut,
                    Activate, UserDetail, EmailVerificationNotice)
from django.urls import path

app_name = 'accounts'

urlpatterns = [
    path('sign-up/', Signup.as_view(), name='sign-up'),
    path('sign-in/', SignIn.as_view(), name='sign-in'),
    path('sign-out/', SignOut.as_view(), name='sign-out'),
    path('activate/<str:uid>/<str:token>', Activate.as_view(), name='activate'),
    path('verification-notice/',
         EmailVerificationNotice.as_view(), name='notice'),
    path('my-account/', UserDetail.as_view(), name='detail'),
]

posts/urls.py
from .views import PostCreateView, PostDetailView, PostListView, PostLikeView
from django.urls import path

app_name = 'posts'

urlpatterns = [
    path('create/', PostCreateView.as_view(), name='new-post'),
    path('', PostListView.as_view(), name='list'),
    path('<int:pk>/', PostDetailView.as_view(), name='detail'),
    path('like/<int:post_id>/', PostLikeView.as_view(), name='like'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>DB2 test challenge {% block title %} {% endblock %}</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/MaterialDesign-Webfont/2.1.19/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.blue_grey-red.min.css"/>
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,500,700" type="text/css">

    <script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>
</head>
<body>

<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
    <header class="mdl-layout__header">
        <div class="mdl-layout__header-row">
            <!-- Title -->
            <a href="{% url 'posts:list' %}" style="padding: 0;" class="mdl-layout-title mdl-navigation__link">Posts</a>
            {% if not user.is_authenticated %}
                <a class="mdl-navigation__link" href="{% url 'accounts:sign-in' %}">Sign In</a>
                <a class="mdl-navigation__link" href="{% url 'accounts:sign-up' %}">Sign Up</a>
            {% else %}
                <a class="mdl-navigation__link" href="{% url 'posts:new-post' %}">New post</a>
                <a class="mdl-navigation__link" href="{% url 'accounts:sign-out' %}">Sign Out</a>
                <a class="mdl-navigation__link" href="{% url 'accounts:detail' %}">Hi, {{ user.email }}!</a>
            {% endif %}
        </div>
    </header>
    <main class="mdl-layout__content">
        <div class="page-content">
            {% block login %}
            {% endblock %}

            {% block content %}
            {% endblock %}
        </div>
    </main>
</div>
</body>
</html>